title: My Learnings
description: I share my learnings here
theme: just-the-docs

url: https://sandeepmadve.github.io/my-learnings

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/sandeepmadve/my-learnings
